# Site settings
title: A journey in open-source software land.
header-img: img/lotr-welcome-page.jpg
email: laferriere.phil@gmail.com
description: >
    This blog's goal is to share to fellow programmers my experiences in contributing to
    open-source software. The first project that I will undertake is the popular node.js.  
baseurl: "http://plafer.github.io"
github_username:  plafer
linkedin_username: profile/view?id=301451294&trk=nav_responsive_tab_profile
include_rssfeed: false

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
#paginate_path: "/patate/page:num/"
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Running locally
# Command: jekyll serve --watch --baseurl ""